# Generated by Django 4.2.9 on 2024-02-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_cartitem_quantity_alter_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=5),
        ),
    ]
